---
# Source: simplerest/charts/couchdb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hw2-couchdb
  labels:
    app: couchdb
    chart: couchdb-3.3.4
    release: hw2
    heritage: Helm
