[micro_iam]

### For Testing only!!!

jwtAudience = "vEwzbcasJVQm1jVYHUHCjhxZ4tYa"
jwtExpTimeInSeconds = 3600
jwtP12Path = "./resources/jwt.p12"
jwtP12Password = "ICEGSckINg0jT949x7LG"
jwtKeyAlias = "jwt_store"
jwtKeyPassword = "ICEGSckINg0jT949x7LG"

httpsP12Path = "./resources/https.p12"
httpsP12Password = "UBMkNk3Smveseer3mVdi"

redisUri = "localhost:6379"