---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: {{.Values.general.lable}}
  name: '{{.Release.Name}}-service'
spec:
  ports:
    - name: 'http-{{.Release.Name}}-service'
      port: {{.Values.deployment.port}}
      protocol: {{.Values.deployment.protocol}}
      targetPort: {{.Values.deployment.port}}
  selector:
    app: {{.Values.general.lable}}
  type: {{.Values.service.type}}
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: {{.Values.general.lable}}
    type: monitoring
  name: '{{.Release.Name}}-monitoring-service'
spec:
  ports:
    - name: monitoring
      port: 9797
      protocol: TCP
      targetPort: 9797
  selector:
    app: {{.Values.general.lable}}
  type: ClusterIP