---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{.Release.Name}}-service-monitor'
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      type: monitoring
      app: {{.Values.general.lable}}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{.Release.Name}}-couchdb-monitor'
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: prometheus-couchdb-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http


