---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: {{.Values.deployment.bff.lable}}
  name: '{{.Release.Name}}-{{.Values.deployment.bff.lable}}-service'
spec:
  ports:
    - name: 'http-{{.Values.deployment.bff.lable}}-service'
      port: {{.Values.deployment.bff.port}}
      protocol: {{.Values.deployment.bff.protocol}}
      targetPort: {{.Values.deployment.bff.port}}
  selector:
    app: {{.Values.deployment.bff.lable}}
  type: {{.Values.service.type}}
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: {{.Values.deployment.iam.lable}}
  name: '{{.Release.Name}}-{{.Values.deployment.iam.lable}}-service'
spec:
  ports:
    - name: 'http-{{.Values.deployment.iam.lable}}-service'
      port: {{.Values.deployment.iam.port}}
      protocol: {{.Values.deployment.iam.protocol}}
      targetPort: {{.Values.deployment.iam.port}}
  selector:
    app: {{.Values.deployment.iam.lable}}
  type: {{.Values.service.type}}
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: {{.Values.deployment.reg.lable}}
  name: '{{.Release.Name}}-{{.Values.deployment.reg.lable}}-service'
spec:
  ports:
    - name: 'http-{{.Values.deployment.reg.lable}}-service'
      port: {{.Values.deployment.reg.port}}
      protocol: {{.Values.deployment.reg.protocol}}
      targetPort: {{.Values.deployment.reg.port}}
  selector:
    app: {{.Values.deployment.reg.lable}}
  type: {{.Values.service.type}}
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: {{.Values.deployment.profile.lable}}
  name: '{{.Release.Name}}-{{.Values.deployment.profile.lable}}-service'
spec:
  ports:
    - name: 'http-{{.Values.deployment.profile.lable}}-service'
      port: {{.Values.deployment.profile.port}}
      protocol: {{.Values.deployment.profile.protocol}}
      targetPort: {{.Values.deployment.profile.port}}
  selector:
    app: {{.Values.deployment.profile.lable}}
  type: {{.Values.service.type}}      