openapi: 3.0.1
info:
  title: micro-iam
  description: IAM Service
  version: 0.0.1

servers:
  - url: https://micro-iam
    description: Deynamic hostname

paths:
  /createToken:
    post:
      tags:
        - iamEp
      summary: Create new JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: testuser
                password:
                  type: string
                  example: testpassword123
      responses:
        "200":
          description: JWT created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "400":
          description: Unable to create JWT!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Wrong login or password!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal error!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /refreshToken:
    post:
      tags:
        - iamEp
      summary: Update JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentJwt:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        "200":
          description: JWT updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  newJwt:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "403":
          description: Problem with sub field in JwtToken!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Invalid current JWT!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal error!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: Unable to create JWT!
