{
 "title": "HW3",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Quantile",
    "query": "\"0.5\", \"0.95\", \"0.99\", \"0.999\""
   },
   {
    "name": "Couch_GC_Quantile",
    "query": "\"0\", \"0.25\", \"0.5\", \"0.75\", \"1\""
   }
  ]
 },
 "panels": [
  {
   "title": "HW3 Service CPU/RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\",  pod=~\".*.deployment.+\"}[5m])) by (pod_name) ",
     "legendFormat": "CPU(vCore)"
    },
    {
     "expr": "round(sum(container_memory_usage_bytes{namespace=\"default\",  pod=~\".*.deployment.+\"})/1024/1204)",
     "legendFormat": "RAM(Mb)"
    }
   ]
  },
  {
   "title": "HW3 Service RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ballerina_http_Caller_requests_total_value[1h]))",
     "legendFormat": "HTTP RPS"
    }
   ]
  },
  {
   "title": "HW3 Service Error 5xx Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ballerina_http_Caller_5XX_requests_total_value[1h]))",
     "legendFormat": "HTTP 5xx Errors"
    }
   ]
  },
  {
   "title": "HW3 Service Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_response_time_seconds{exported_service=\"users\", quantile=\"$Quantile\", http_method=\"GET\"}[1h]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(rate(http_response_time_seconds{exported_service=\"users\", quantile=\"$Quantile\", http_method=\"POST\"}[1h]))",
     "legendFormat": "POST"
    },
    {
     "expr": "avg(rate(http_response_time_seconds{exported_service=\"users\", quantile=\"$Quantile\", http_method=\"PUT\"}[1h]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(rate(http_response_time_seconds{exported_service=\"users\", quantile=\"$Quantile\", http_method=\"DELETE\"}[1h]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Ingress Latency With Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($Quantile, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Ingress Latency (response time)"
    }
   ]
  },
  {
   "title": "Ingress Latency Without Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum{namespace=\"ingress-nginx\"}[5m])) / sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count{namespace=\"ingress-nginx\"}[5m])) * 1000",
     "legendFormat": "Latency (response time)"
    }
   ]
  },
  {
   "title": "Ingress 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\",namespace=\"ingress-nginx\"}[5m])) / sum(rate(nginx_ingress_controller_requests{namespace=\"ingress-nginx\"}[5m])) * 100",
     "legendFormat": "Nginx HTTP 5xxx Error Rate"
    }
   ]
  },
  {
   "title": "Ingress RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m])) by (status_code)",
     "legendFormat": "Ingress RPS"
    }
   ]
  },
  {
   "title": "CouchDB GC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\", quantile=\"$Couch_GC_Quantile\"}",
     "legendFormat": "GC Duration Seconds"
    },
    {
     "expr": "round(go_memstats_gc_sys_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "GC Memstats Sys Mb"
    },
    {
     "expr": "round(go_memstats_next_gc_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "GC Memstats Next Mb"
    }
   ]
  },
  {
   "title": "CouchDB Process Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(process_virtual_memory_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Process vRAM Mb"
    },
    {
     "expr": "process_open_fds{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}",
     "legendFormat": "Open File Descriptors"
    },
    {
     "expr": "process_cpu_seconds_total{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}",
     "legendFormat": "CPU Usage Seconds"
    }
   ]
  },
  {
   "title": "CouchDB Heap",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(go_memstats_heap_alloc_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Heap Alloc Mb"
    },
    {
     "expr": "round(go_memstats_heap_idle_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Heap Idle Mb"
    },
    {
     "expr": "round(go_memstats_heap_inuse_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Heap InUse Mb"
    },
    {
     "expr": "go_memstats_heap_objects{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}",
     "legendFormat": "Heap Objects"
    },
    {
     "expr": "round(go_memstats_heap_released_bytes_total{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Heap Released Mb Total"
    },
    {
     "expr": "round(go_memstats_heap_sys_bytes{namespace=\"default\", pod=~\".*.-prometheus-couchdb-exporter.+\"}/1024/1024)",
     "legendFormat": "Heap Sys Mb"
    }
   ]
  }
 ]
}